/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.io.FileOutputStream;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.PreparedStatement;

import java.sql.ResultSet;
import java.text.MessageFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;

/**
 *
 * @author yared
 */
public class ViewAllRecords extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllRecords
     */
    DefaultTableModel model;
    public ViewAllRecords() {
        initComponents();
        setStudentDetailsToTable();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }
    //to set the book details into the table
   public void setStudentDetailsToTable(){
        try{
             String driver="com.mysql.cj.jdbc.Driver";
            String datbaseurl="jdbc:mysql://localhost:3306/universitylibrary";
            String username="root";
            String password="";
            Class.forName(driver);
           java.sql.Connection conn=DriverManager.getConnection(datbaseurl,username,password);
           Statement st=conn.createStatement();
           ResultSet rs=st.executeQuery("select *from issue_book_details");
           while(rs.next()){
               String id=rs.getString("book_id");
               String bookName=rs.getString("book_name");
               String StudentName=rs.getString("student_name");
               String issueDate=rs.getString("issue_date");
               String dueDate=rs.getString("due_date");
               String status=rs.getString("status");
               
               
               Object[] obj={id,bookName,StudentName,issueDate,dueDate,status};
                 DefaultTableModel model = (DefaultTableModel)issuebook.getModel();
                 model.addRow(obj);
               
           }
           
           
        }catch(Exception e){
            e.printStackTrace();
        }
    }
   //to fetch the record using date fields
   public void search(){
       Date  uFromDate=Date_dueDate.getDatoFecha();
       Date uToDate=Date_issueDate.getDatoFecha();
        long l1=uFromDate.getTime();
        long l2=uToDate.getTime();
        
        java.sql.Date fromDate=new java.sql.Date(l1);
        java.sql.Date toDate=new java.sql.Date(l2);
        
        try{
            String driver="com.mysql.cj.jdbc.Driver";
            String datbaseurl="jdbc:mysql://localhost:3306/universitylibrary";
            String username="root";
            String password="";
            Class.forName(driver);
           java.sql.Connection conn=DriverManager.getConnection(datbaseurl,username,password);
               String sql="select *from issue_book_details where issue_date BETWEEN ? and ?";
               PreparedStatement pst=conn.prepareStatement(sql);
               pst.setDate(1,fromDate);
               pst.setDate(2, toDate);
        
               
                ResultSet rs= pst.executeQuery();
              
              if(rs.next()==false){
                  JOptionPane.showMessageDialog(this, "No Record Found");
              }   else{ 
              while(rs.next()){
               String id=rs.getString("book_id");
               String bookName=rs.getString("book_name");
               String StudentName=rs.getString("student_name");
               String issueDate=rs.getString("issue_date");
               String dueDate=rs.getString("due_date");
               String status=rs.getString("status");
               
               
               Object[] obj={id,bookName,StudentName,issueDate,dueDate,status};
                 DefaultTableModel model = (DefaultTableModel)issuebook.getModel();
                 model.addRow(obj);
                }
              }
               
        }catch(Exception e){
            e.printStackTrace();
        }
   }

    //method to clear table
   public void clearTable(){
        DefaultTableModel model=(DefaultTableModel)issuebook.getModel();
        model.setRowCount(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Date_issueDate = new rojeru_san.componentes.RSDateChooser();
        Date_dueDate = new rojeru_san.componentes.RSDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        jLabel1 = new javax.swing.JLabel();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();
        report = new rojerusan.RSMaterialButtonRectangle();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        issuebook = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/Science-Courses-icon (1).png"))); // NOI18N
        jLabel11.setText("View all  Record ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 310, 90));

        jLabel12.setBackground(new java.awt.Color(255, 0, 51));
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 200, 10));

        Date_issueDate.setBackground(new java.awt.Color(255, 102, 0));
        Date_issueDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Date_issueDate.setColorBackground(new java.awt.Color(255, 102, 0));
        Date_issueDate.setColorSelForeground(new java.awt.Color(0, 102, 204));
        Date_issueDate.setColorTextDiaActual(new java.awt.Color(255, 153, 0));
        Date_issueDate.setPlaceholder("end_date");
        jPanel2.add(Date_issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 251, -1));

        Date_dueDate.setBackground(new java.awt.Color(255, 102, 0));
        Date_dueDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Date_dueDate.setColorBackground(new java.awt.Color(255, 153, 0));
        Date_dueDate.setColorSelForeground(new java.awt.Color(0, 102, 204));
        Date_dueDate.setColorTextDiaActual(new java.awt.Color(0, 102, 204));
        Date_dueDate.setPlaceholder("start_date");
        jPanel2.add(Date_dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 251, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 51));
        jLabel16.setText("Due Date");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 51));
        jLabel17.setText("Issue Date");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(0, 0, 102));
        rSMaterialButtonRectangle1.setText("All");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, 100, 50));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/back (1).png"))); // NOI18N
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        rSMaterialButtonRectangle3.setBackground(new java.awt.Color(255, 51, 0));
        rSMaterialButtonRectangle3.setText("Search");
        rSMaterialButtonRectangle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle3ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonRectangle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 100, 50));

        report.setBackground(new java.awt.Color(255, 204, 0));
        report.setForeground(new java.awt.Color(51, 51, 51));
        report.setText("report");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        jPanel2.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 210, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 209));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        issuebook.setForeground(new java.awt.Color(255, 255, 0));
        issuebook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Book_Name", "Student Name", "Issue Date", "Due Date", "Status"
            }
        ));
        issuebook.setColorBackgoundHead(new java.awt.Color(255, 51, 0));
        issuebook.setColorBordeFilas(new java.awt.Color(0, 0, 102));
        issuebook.setColorBordeHead(new java.awt.Color(255, 51, 0));
        issuebook.setColorFilasBackgound1(new java.awt.Color(255, 255, 0));
        issuebook.setColorFilasBackgound2(new java.awt.Color(153, 204, 255));
        issuebook.setColorForegroundHead(new java.awt.Color(255, 255, 0));
        issuebook.setFont(new java.awt.Font("Verdana", 1, 8)); // NOI18N
        issuebook.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        issuebook.setRowHeight(30);
        issuebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issuebookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(issuebook);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1040, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        HomePage home=new HomePage();
        home.setVisible(true);
         dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        // TODO add your handling code here:
             clearTable();
             setStudentDetailsToTable();
   
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    
    private void issuebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuebookMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_issuebookMouseClicked

    private void rSMaterialButtonRectangle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle3ActionPerformed
        // TODO add your handling code here:
           clearTable();
        search();
    }//GEN-LAST:event_rSMaterialButtonRectangle3ActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
            MessageFormat header=new MessageFormat(" Harmbee University Labirary MS");
        MessageFormat footer=new MessageFormat("Page {0, number, integer }");
        try {
            issuebook.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (java.awt.print.PrinterException ex) {
            System.err.format("Cannot print ",ex.getMessage());
        }

    
    }//GEN-LAST:event_reportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.componentes.RSDateChooser Date_dueDate;
    private rojeru_san.componentes.RSDateChooser Date_issueDate;
    private rojeru_san.complementos.RSTableMetro issuebook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    private rojerusan.RSMaterialButtonRectangle report;
    // End of variables declaration//GEN-END:variables
}
